RegisterNetEvent("plouffe_fleeca:sendConfig", Fle.LoadPlayer)
RegisterNetEvent("plouffe_fleeca:hacking_finished", Fle.StartRobbery)
RegisterNetEvent("plouffe_fleeca:hacking_failed", Fle.HackingFailed)
RegisterNetEvent("plouffe_fleeca:requestLoots", Fle.RequestLoots)
RegisterNetEvent("plouffe_fleeca:finished_thermal", Fle.FinishedThermal)
RegisterNetEvent("plouffe_fleeca:destroyLoots", Fle.DestroyLoots)
RegisterNetEvent("plouffe_fleeca:lockpickedDoor", Fle.PlayerUnlockedDoor)